name: Manual Trigger Workflow

on:
  workflow_dispatch: # This event allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run a sample script
      run: eas build -p android --profile preview
